postgresDbUrl: jdbc:postgresql://localhost:5432/postgres
ddRidersDbUrl: jdbc:postgresql://localhost:5432/dd_riders_db
user: postgres
password: pinkblink
pathToCreateDbScript: sql/create_db_script.sql
pathToCreateTablesScript: sql/create_tables_script.sql
accessTokenTtl: 600
refreshTokenTtl: 6000
signature: dirtydickridersforever